QuantumQuiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('genQuiz.urls', namespace='genQuiz')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}),

]

# Add the following line to serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genQuiz/urls.py
from django.urls import path
from .views import *

app_name = 'genQuiz'

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('genQuiz/', genQuiz, name='genQuiz'),
    path('generate/', generate, name='generate'),
    path('profile/', profile, name='profile'),
]

genQuiz/models.py
from django.db import models
from django.contrib.auth.models import User

class Quiz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.TextField()
    option1 = models.TextField()
    option2 = models.TextField()
    option3 = models.TextField(blank=True)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

genQuiz/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import os
import PyPDF2
from .models import Quiz
from generateQuiz.makeQuiz import generateQuiz

# Create your views here.
def home(request):
    login_form = AuthenticationForm()
    signup_form = UserCreationForm()
    context = {'login_form': login_form, 'signup_form': signup_form}
    return render(request, 'index.html', context)

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('genQuiz:home')  # Redirect to the home page after login

    login_form = AuthenticationForm()
    signup_form = UserCreationForm()
    context = {'login_form': login_form, 'signup_form': signup_form}
    return render(request, 'index.html', context)

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('genQuiz:home')  # Redirect to the home page after sign up

    login_form = AuthenticationForm()
    signup_form = UserCreationForm()
    context = {'login_form': login_form, 'signup_form': signup_form}
    return redirect('genQuiz:home')

def logout_view(request):
    logout(request)
    return redirect('genQuiz:home')

def genQuiz(request):
    return render(request, 'genQuiz.html')

@login_required
def profile(request):
    questions = Quiz.objects.filter(user=request.user).order_by('-created_at')
    context = {'quizzez': questions}
    return render(request, 'displayQuizzes.html', context)

@login_required
def generate(request):
    if request.method == 'POST':
        # Process the form data
        question_type = request.POST.get('questionType')
        context_type = request.POST.get('contextType')
        difficulty_level = request.POST.get('difficultyLevel')
        question_quantity = request.POST.get('quantity')
        document = [] # stores document type and destination

        data = { # stores all data from form
            'q_type':question_type,
            'con_type': context_type,
            'difficulty': difficulty_level,
            'quantity': question_quantity,
        }


        if context_type == 'document':
            uploaded_file = request.FILES['document']

            file_name = uploaded_file.name
            file_extension = file_name.split('.')[-1]  # Get file extension
            username = request.user.username # get username
            #Handle pdf file and save it
            if file_extension.lower() == 'pdf':
                # Get uploaded file and save it to a data/docs folder
                # Define the file path
                file_path = f'generateQuiz/type2text/data/docs/{username}.pdf'
                # Create the directory if it doesn't exist
                try:
                    os.makedirs(os.path.dirname(file_path), exist_ok=True)
                    print('file created')
                except OSError as e:
                    print(f"Error creating directory: {e}")

                with open(f'generateQuiz/type2text/data/docs/{request.user.username}.pdf', 'wb+') as destination:
                    for chunk in uploaded_file.chunks():
                        destination.write(chunk)

                print('file written')
                with uploaded_file.open() as f:
                    reader = PyPDF2.PdfReader(f)
                    num_pages = len(reader.pages)               
                startPage = int(request.POST.get('startPage'))
                endPage = int(request.POST.get('endPage'))
                if startPage<1 or endPage>num_pages+1:
                    return JsonResponse({'message': 'Input Correct range of start and end numbers for the file!'})
                elif endPage - startPage<0:
                    return JsonResponse({'message': 'End number should be greater than start number!'})
                
                document = [file_extension, f'generateQuiz/type2text/data/docs/{username}.pdf', startPage, endPage+1]

                # Optionally, we can save information about the uploaded file in our database
            else:
                # Get uploaded file and save it to a data/docs folder
                # Define the file path
                file_path = f'generateQuiz/type2text/data/docs/{username}.docx'
                # Create the directory if it doesn't exist
                try:
                    os.makedirs(os.path.dirname(file_path), exist_ok=True)
                except OSError as e:
                    print(f"Error creating directory: {e}")
                # Get uploaded file and save it to a data/docs folder
                with open(f'generateQuiz/type2text/data/docs/{username}.docx', 'wb+') as destination:
                    for chunk in uploaded_file.chunks():
                        destination.write(chunk)

                doc = docx.Document(uploaded_file)
                num_pages = len(doc.paragraphs)

                startPage = int(request.POST.get('startPage'))
                endPage = int(request.POST.get('endPage'))

                if startPage<1 or endPage>num_pages:
                    return JsonResponse({'message': 'Input Correct range of start and end numbers for the file!'})
                elif endPage - startPage<0:
                    return JsonResponse({'message': 'End number should be greater than start number!'})
                
                document = [file_extension, f'generateQuiz/type2text/data/docs/{username}.docx', startPage-1, endPage]
            data['doc'] = document       
        elif context_type == 'url':
            url = request.POST.get('url')
            data['url'] = url
        else:
            text = request.POST.get('text')
            data['text'] = text
        
        questions = generateQuiz(data) # call this function to generate questions based on data
        print(questions)
        for quiz in questions:
            # Common fields for all question types
            common_fields = {
                'user': request.user,
                'question': quiz['question'],

            }
            print(data['q_type'])
            if data['q_type'] == 'MCQ':
                # Additional fields for multiple-choice questions
                data_model_instance = Quiz(
                    **common_fields,
                    answer= quiz['answer'],
                    option1=quiz['option1'],
                    option2=quiz['option2'],
                    option3=quiz['option3'],
                )
            elif data['q_type'] == 'True or False questions':
                # Additional fields for true/false questions
                data_model_instance = Quiz(
                    **common_fields,
                    option1=quiz['option1'],
                    option2=quiz['option2'],
                    answer= quiz['answer'],
                )
            else:
                # Additional fields for other question types
                data_model_instance = Quiz(
                    **common_fields,
                    option1=quiz['hint1'],
                    option2=quiz['hint2'],
                    option3=quiz['hint3'],
                    answer= quiz['answer'],
                )
            
            # Save the data model instance
            data_model_instance.save()

    return redirect('genQuiz:profile')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuantumQuiz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">

      <link
        rel="stylesheet"
        href="https://site-assets.fontawesome.com/releases/v6.5.2/css/all.css"
      >

      <link
        rel="stylesheet"
        href="https://site-assets.fontawesome.com/releases/v6.5.2/css/sharp-thin.css"
      >

      <link
        rel="stylesheet"
        href="https://site-assets.fontawesome.com/releases/v6.5.2/css/sharp-solid.css"
      >

      <link
        rel="stylesheet"
        href="https://site-assets.fontawesome.com/releases/v6.5.2/css/sharp-regular.css"
      >

      <link
        rel="stylesheet"
        href="https://site-assets.fontawesome.com/releases/v6.5.2/css/sharp-light.css"
      >

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'genQuiz:home' %}"><i class="fa-regular fa-q"></i>uantum<i class="fa-regular fa-q"></i>uiz</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a href="{% url 'genQuiz:logout' %}"><button class="btn exit-btn"><i class="fa-solid fa-arrow-left-from-bracket" style="color: azure;"></i></button></a>
                    {% else %}
                    <button class="btn btn-primary login-btn" data-toggle="modal" data-target="#loginSignupModal"><i class="fas fa-sign-in-alt"></i></button>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <button class="btn exit-btn"><a href="{% url 'genQuiz:profile' %}"><i class="fa-solid fa-user" style="color: azure;"></i></a></button>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            // Switch to Sign Up form
            $("#switchToSignup").click(function(){
                $("#loginForm").hide();
                $("#signupForm").show();
                $(this).hide();
                $("#switchToLogin").show();
            });
            // Switch to Login form
            $("#switchToLogin").click(function(){
                $("#signupForm").hide();
                $("#loginForm").show();
                $(this).hide();
                $("#switchToSignup").show();
            });
            // Hover effect for switch links
            $("#switchToSignup a, #switchToLogin a").hover(function(){
                $(this).css("cursor", "pointer");
            }, function(){
                $(this).css("cursor", "default");
            });
        });
    </script>
</body>
</html>

templates/displayQuizzes.html
{% extends 'base.html' %}
{% load static %}


{% block content %}  

<section>
    <div class="container">
        <h1 class="mt-4 mb-4 text-center">User Questions</h1>
        <div class="row">
            {% for question in quizzez %}
            <div class="col-md-6 p-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ question.question }}</h5>
                        <ul class="list-unstyled">
                            <li>Option 1: {{ question.option1 }}</li>
                            <li>Option 2: {{ question.option2 }}</li>
                            {% if question.option3 %}
                            <li>Option 3: {{ question.option3 }}</li>
                            {% endif %}
                            <li id="answer{{ forloop.counter }}" class="d-none">Answer: {{ question.answer }}</li>
                        </ul>
                        <button class="btn btn-primary show-answer-btn" data-answer-id="answer{{ forloop.counter }}">Show Answer</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% if not quizzez %}
<section class='generate-quiz container d-flex justify-content-center text-center'>
    <button class="btn btn-danger" style="padding: 2% 5%; border-radius: 500px;"><a href="{% url 'genQuiz:genQuiz' %}" style="color: white; text-decoration: none; font-size: 250%;">Generate Quiz!</a></button>
</section>
{% endif %}


<script>
    document.addEventListener('DOMContentLoaded', function() {
        const showAnswerButtons = document.querySelectorAll('.show-answer-btn');

        showAnswerButtons.forEach(button => {
            button.addEventListener('click', function() {
                const answerId = this.dataset.answerId;
                const answerElement = document.getElementById(answerId);
                answerElement.classList.toggle('d-none');
                
                // Toggle button text
                if (this.innerText === 'Show Answer') {
                    this.innerText = 'Hide Answer';
                } else {
                    this.innerText = 'Show Answer';
                }
            });
        });
    });
</script>

{% endblock %}

templates/genQuiz.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section>
    <div class="container">
        <h1 class="text-center pt-3">Question Generation</h1>
        <form method="post" id="FormId">
            {% csrf_token %}
            <div class="form-group">
                <label for="questionType">Question Type:</label>
                <select class="form-control" id="questionType" name="questionType">
                    <option value="" selected disabled>Select Question Type</option>
                    <option value="mcq">Multiple Choice Questions</option>
                    <option value="shaq">Short answer questions</option>
                    <option value="tfq">True or False questions</option>
                    <option value="psq">Real World Problem Solving questions</option>
                    <!-- Add options for other question types if needed -->
                </select>
            </div>
            <div class="form-group">
                <label for="contextType">Context Type:</label>
                <select class="form-control" id="contextType" name="contextType">
                    <option value="" selected disabled>Select Context Type</option>
                    <option value="document">Document</option>
                    <option value="url">Link</option>
                    <option value="text">Text</option>
                </select>
            </div>

            <!-- Document Field (hidden by default) -->
            <div class="form-group" id="documentField" style="display: none;">
                <label for="document">Upload Document (PDF or Word):</label>
                <input type="file" class="form-control-file" id="document" name="document" accept=".pdf,.doc,.docx">
                
                <div class="form-row mt-3">
                    <div class="col">
                        <label for="startPage">Start Page:</label>
                        <input type="number" class="form-control" id="startPage" name="startPage" placeholder="Start Page">
                    </div>
                    <div class="col">
                        <label for="endPage">End Page:</label>
                        <input type="number" class="form-control" id="endPage" name="endPage" placeholder="End Page">
                    </div>
                </div>
            </div>


            <!-- URL Field (hidden by default) -->
            <div class="form-group" id="urlField" style="display: none;">
                <label for="url">Enter Link:</label>
                <input type="url" class="form-control" id="url" name="url" placeholder="https://example.com">
            </div>
        
            <!-- Text Field (hidden by default) -->
            <div class="form-group" id="textField" style="display: none;">
                <label for="text">Just paste the text to generate quiz:</label>
                <textarea class="form-control" id="text" name="text" rows="4"></textarea>
            </div>
        
            <div class="form-group">
                <label for="difficultyLevel">Difficulty Level:</label>
                <select class="form-control" id="difficultyLevel" name="difficultyLevel">
                    <option value="" selected disabled>Select Difficulty Level</option>
                    <option value="easy">Easy</option>
                    <option value="medium">Medium</option>
                    <option value="hard">Hard</option>
                </select>
            </div>
            <!-- Quantity Field -->
            <div class="form-group" id="documentField">
                <label for="">Enter Question quantity</label>
                <input type="number" class="form-control" name="quantity" placeholder="Quantity">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        
    </div>
</section>


<script>
// Send form data to backend to further processing
document.addEventListener("DOMContentLoaded", function () {
    var form = document.getElementById("FormId");

    form.addEventListener("submit", function (event) {
        event.preventDefault(); // Prevent the default form submission
        
        // Serialize form data
        var formData = new FormData(form);
        
        // Send an AJAX request
        fetch("{% url 'genQuiz:generate' %}", {
            method: "POST",
            body: formData
        })
        .then(() => {
            // Form data sent successfully, no need to handle response
            console.log("Form data sent successfully");
            alert("Quizzes created successfully!");
        })
        .catch(error => {
            // Handle errors
            console.error("There was a problem with sending the form data:", error);
        });
    });
});



document.getElementById("document").addEventListener("change", function() {
    var file = this.files[0];
    if (file) {
        var reader = new FileReader();
        reader.onload = function(e) {
            var text = e.target.result;
            // Here you can extract the start and end page numbers from the text
            // For demonstration, let's assume they are extracted as startPageNumber and endPageNumber

            // Set the values of startPage and endPage fields
            document.getElementById("startPage").placeholder = "Enter reasonable number";
            document.getElementById("endPage").placeholder = "Enter reasonable number";
        };
        reader.readAsText(file);
    }
});

    document.addEventListener("DOMContentLoaded", function () {
        var contextTypeSelect = document.getElementById("contextType");
        var documentField = document.getElementById("documentField");
        var urlField = document.getElementById("urlField");
        var textField = document.getElementById("textField");

        // Initially hide all fields
        documentField.style.display = "none";
        urlField.style.display = "none";
        textField.style.display = "none";

        contextTypeSelect.addEventListener("change", function () {
            var selectedContext = contextTypeSelect.value;

            // Hide all fields
            documentField.style.display = "none";
            urlField.style.display = "none";
            textField.style.display = "none";

            // Show the selected field based on the context type
            if (selectedContext === "document") {
                documentField.style.display = "block";
            } else if (selectedContext === "url") {
                urlField.style.display = "block";
            } else if (selectedContext === "text") {
                textField.style.display = "block";
            }
        });
    });
    
</script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Login/Signup Modal -->
    <div class="modal fade" id="loginSignupModal" tabindex="-1" role="dialog" aria-labelledby="loginSignupModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginSignupModalLabel">Login / Sign Up</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Login form -->
                    <form method="post" action="{% url 'genQuiz:login' %}" id="loginForm">
                        {% csrf_token %}
                        {{ login_form.as_p }}
                        <button type="submit" class="btn btn-primary">Login</button>
                        
                    </form>
                    <!-- Signup form (hidden by default) -->
                    <form method="post" action = "{% url 'genQuiz:signup' %}" id="signupForm" style="display: none;">
                        {% csrf_token %}
                        {{ signup_form.as_p }}
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                    </form>
                </div>
                
                <div class="modal-footer">
                    <p id="switchToSignup">Don't have account? <a>Sign Up</a></p>
                    <p style="display: none;" id="switchToLogin">Already have account? <a>Login</a></p>
                </div>
            </div>
        </div>
    </div>
    <main>
        <section style="color: #222222; margin-top: 2.5%;">
            <h2 class="text-center">Create Quizzes from different sources!</h2>
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3 d-flex justify-content-center align-items-center">
                                        <i class="fa-regular fa-wand-magic-sparkles" style="font-size: 400%;"></i>
                                    </div>                                    
                                    <div class="col-9">
                                        <p> Generate from Text <a style="background-color: #EEE9F4; color: #8854C0; border-radius: 5px; padding:2px 10px;"><i class="fa-solid fa-sparkles"></i> AI</a></p>
                                        <p>Prompt the Al or paste your own text</p>
                                    </div>
                                </div>
                                <div class="container d-flex justify-content-around card-elements">
                                    <img src="{% static 'assets/img/ctrl+c.png' %}"  style="padding: 5px; width: 50%;" alt=""><br>
                                    <img src="{% static 'assets/img/ctrl+v.png' %}"  style="padding: 5px; width: 50%;"  alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3 d-flex justify-content-center align-items-center">
                                        <i class="fa-regular fa-file-arrow-up" style="font-size: 400%;"></i>
                                    </div>                                    
                                    <div class="col-9">
                                        <p>Upload a document <a style="background-color: #EEE9F4; color: #8854C0; border-radius: 5px; padding:2px 10px;"><i class="fa-solid fa-sparkles"></i> AI</a></p>
                                        <p>Transform any PDF, DOC into a quiz</p>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-around card-elements">
                                    <img src="{% static 'assets/img/pdf.png' %}" style="height: 100%; " alt="">
                                    <img src="{% static 'assets/img/doc.png' %}" style="height: 100%; " alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3 d-flex justify-content-center align-items-center">
                                        <i class="fa-regular fa-link" style="font-size: 400%;"></i>
                                    </div>                                    
                                    <div class="col-9">
                                        <p>Convert URL to quiz<a style="background-color: #EEE9F4; color: #8854C0; border-radius: 5px; padding:2px 10px;"><i class="fa-solid fa-sparkles"></i> AI</a></p>
                                        <p>YouTube videos, Wikipedia pages and more</p>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-around card-elements">
                                    <img src="{% static 'assets/img/youtube.png' %}" style="height: 100%;" alt="">
                                    <img src="{% static 'assets/img/wiki.svg' %}" style="height: 100%;" alt="">
                                    <img src="{% static 'assets/img/www.png' %}" style="height: 100%;" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </section>
        {% if user.is_authenticated %}
        <section class='generate-quiz container d-flex justify-content-center text-center'>
            <button class="btn btn-danger" style="padding: 2% 5%; border-radius: 500px;"><a href="{% url 'genQuiz:genQuiz' %}" style="color: white; text-decoration: none; font-size: 250%;">Generate Quiz!</a></button>
        </section>
        
        {% endif %}
    </main>
{% endblock %}